language: node_js
node_js: node
env:
  - TYPESCRIPT_VERSION=next
  - TYPESCRIPT_VERSION=4.0
  - TYPESCRIPT_VERSION=3.9
install:
  - npm ci --ignore-scripts
  - npm install typescript@$TYPESCRIPT_VERSION
script: npm run prepare

jobs:
  include:
    - env:
        - TYPESCRIPT_VERSION=3.8
      install:
        - npm ci --ignore-scripts
        - npm install typescript@$TYPESCRIPT_VERSION
        - sed -i -e 's/"cd type-tests.*"/"true"/' package.json
        - sed -i -e 's/@ts-expect-error/typings:expect-error/' type-tests/files/*
        - mv type-tests/types.test.disabled.ts type-tests/types.test.ts
      script: npm run prepare
    - env:
        - TYPESCRIPT_VERSION=3.7
      install:
        - npm ci --ignore-scripts
        - npm install typescript@$TYPESCRIPT_VERSION
        - sed -i -e 's/"cd type-tests.*"/"true"/' package.json
        - sed -i -e 's/@ts-expect-error/typings:expect-error/' type-tests/files/*
        - mv type-tests/types.test.disabled.ts type-tests/types.test.ts
      script: npm run prepare
    - env:
        - TYPESCRIPT_VERSION=3.6
      install:
        - npm ci --ignore-scripts
        - npm install typescript@$TYPESCRIPT_VERSION
        - sed -i -e 's/"cd type-tests.*"/"true"/' package.json
        - sed -i -e 's/@ts-expect-error/typings:expect-error/' type-tests/files/*
        - mv type-tests/types.test.disabled.ts type-tests/types.test.ts
      script: npm run prepare
    - env:
        - TYPESCRIPT_VERSION=3.5
      install:
        - npm ci --ignore-scripts
        - npm install typescript@$TYPESCRIPT_VERSION
        - sed -i -e 's/"cd type-tests.*"/"true"/' package.json
        - sed -i -e 's/@ts-expect-error/typings:expect-error/' type-tests/files/*
        - mv type-tests/types.test.disabled.ts type-tests/types.test.ts
      script: npm run prepare
